#!/bin/bash

set -uo pipefail

CHIP=${CHIP:-0}
GPIO=${GPIO:-23}

cd "$(dirname "$0")"

# -----------------------------------------------------------------------------
# Colors
# -----------------------------------------------------------------------------

# Reset
COLOR_RESET='\033[0m'

# Regular Colors
COLOR_BLACK='\033[0;30m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_BLUE='\033[0;34m'
COLOR_PURPLE='\033[0;35m'
COLOR_CYAN='\033[0;36m'
COLOR_WHITE='\033[0;37m'

# Bold
COLOR_BLACK_BOLD='\033[1;30m'
COLOR_RED_BOLD='\033[1;31m'
COLOR_GREEN_BOLD='\033[1;32m'
COLOR_YELLOW_BOLD='\033[1;33m'
COLOR_BLUE_BOLD='\033[1;34m'
COLOR_PURPLE_BOLD='\033[1;35m'
COLOR_CYAN_BOLD='\033[1;36m'
COLOR_WHITE_BOLD='\033[1;37m'

# Alias
COLOR_INFO=$COLOR_GREEN_BOLD
COLOR_WARNING=$COLOR_YELLOW_BOLD
COLOR_ERROR=$COLOR_RED_BOLD
COLOR_END=$COLOR_RESET

# -----------------------------------------------------------------------------
# Utils
# -----------------------------------------------------------------------------

INSTALLED_DEPENDENCIES=""
PACKAGES_CACHED=0

dependencyCheck() {
    
    COMMAND=$1
    PACKAGE=${2:-$COMMAND}

    if ! command -v $COMMAND >/dev/null 2>&1
    then
        echo -e "${COLOR_INFO}Installing $COMMAND dependency${COLOR_END}"
        if [ $PACKAGES_CACHED -eq 0 ] 
        then
            sudo apt update
            PACKAGES_CACHED=1
        fi
        sudo apt install -y $PACKAGE
        INSTALLED_DEPENDENCIES="${INSTALLED_DEPENDENCIES}${PACKAGE} "
    fi

}

gpiod_version() {
    if ! command -v  gpioset >/dev/null 2>&1
    then
        echo 0
        return
    fi
    OUTPUT=$( gpioset -v )
    VERSION=$( echo $OUTPUT | cut -d' ' -f 3 |  cut -d'.' -f1 | sed 's/v//' )
    echo $VERSION
}

list_songs() {
  echo
  echo -e "${COLOR_INFO}Existing songs:${COLOR_END}"
  for SONG in `ls ./songs/*.notes`
  do
    SONG=$( echo $SONG | sed 's|./songs/||' | sed 's|.notes||' )
    echo -e "${COLOR_INFO}  * ${SONG}${COLOR_END}"
  done
}

# -----------------------------------------------------------------------------
# Checks
# -----------------------------------------------------------------------------

echo

# Check GPIOd version
if [ $( gpiod_version ) -ne 2 ]
then
  echo -e "${COLOR_ERROR}This code requires GPIOd version 2${COLOR_END}"
  echo
  exit 1
fi

# Show usages if called without parameters
if [ $# -ne 1 ] 
then
  echo -e "${COLOR_ERROR}Usage: $0 <song>${COLOR_END}"
  list_songs
  echo
  exit 2
fi
SONG="$1"

# Check the song exists
if [ ! -e ./songs/$SONG.notes ]; 
then
  echo -e "${COLOR_ERROR}The song does not exist${COLOR_END}"
  list_songs
  echo
  exit 3
fi

# Check dependencies are installed
dependencyCheck bc

# -----------------------------------------------------------------------------
# Load notes & son
# -----------------------------------------------------------------------------

# Load notes and song
. ./notes
. ./songs/$SONG.notes

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

echo -e "${COLOR_INFO}Playing ${SONG}!!${COLOR_END}"
echo

INDEX=0
WHOLENOTE=$(( 240000 / $TEMPO )) # ms

for PART in $MELODY
do
    if [[ $INDEX -eq 0 ]]
    then
        NOTE=$PART
        INDEX=1
    else
        DIVIDER=$PART
        INDEX=0
        if [[ $DIVIDER -gt 0 ]]
        then
            DURATION=$(( $WHOLENOTE / $DIVIDER ))
        else
            DURATION=$(( 3 * $WHOLENOTE / -$DIVIDER / 2))
        fi
        DURATION=$( echo "$DURATION / 1000" | bc -l | xargs printf "%0.3fs" )
        if [[ $NOTE -eq 0 ]];
        then
            timeout --preserve-status $DURATION sleep 10
        else
            DELAY=$(( 500000 / $NOTE )) # us
            timeout --preserve-status $DURATION gpioset -t ${DELAY}us -c $CHIP $GPIO=1
        fi
    fi
done